### ISSUE TITLE
Crash with Colormatic/Fabric Zero/Sodium

### ISSUE THREAD

**Issue by assasin541** [IsaiahMC/thallium#29]
[22:54:56] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8469(int)" because "?" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47) ~[?:?]
	at net.minecraft.network.packet.s2c.play.EntityS2CPacket.getEntity(EntityS2CPacket:182) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onEntityUpdate(ClientPlayNetworkHandler:622) ~[?:?]
	at net.minecraft.network.packet.s2c.play.EntityS2CPacket.apply(EntityS2CPacket:172) ~[?:?]
	at net.minecraft.network.packet.s2c.play.EntityS2CPacket$MoveRelative.apply(EntityS2CPacket:89) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.MinecraftClient.handler$zhm000$afterCrashHandled(MinecraftClient:4904) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:704) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[22:54:56] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_8469(int)" because "this.field_3699" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onEntityTrackerUpdate(ClientPlayNetworkHandler:566) ~[?:?]

**Comment by BlunderG** [comment]
Especially with the Sodium.

**Comment by JeffAxe123** [comment]
https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec
