### ISSUE TITLE
Crash on launch with Fabrication

### ISSUE THREAD

**Issue by IdrisQe** [IsaiahMC/thallium#30]
Fabrication 1.3.3, Thallium 1.10, Minecraft 1.16.5
Thallium PlayerEntityMixin error in relation to particles added by Fabrication, it seems?

```
[15:38:51] [main/INFO]: Instancing error handler class com.unascribed.fabrication.support.MixinErrorHandler
[15:38:51] [main/FATAL]: Mixin apply failed zoob.mixins.json:PlayerEntityMixin -> net.minecraft.class_1657: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1657::addParticles with priority 1000 cannot inject into net/minecraft/class_1657::method_5773()V merged by thallium.fabric.mixins.general.MixinPlayerEntity with priority 1000 [PREINJECT Applicator Phase -> zoob.mixins.json:PlayerEntityMixin -> Prepare Injections ->  -> handler$def000$addParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1657::addParticles with priority 1000 cannot inject into net/minecraft/class_1657::method_5773()V merged by thallium.fabric.mixins.general.MixinPlayerEntity with priority 1000 [PREINJECT Applicator Phase -> zoob.mixins.json:PlayerEntityMixin -> Prepare Injections ->  -> handler$def000$addParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.2.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.2.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_281]
	at carpetextra.CarpetExtraServer.<clinit>(CarpetExtraServer.java:26) [carpet-extra-1.16.5-1.4.27.jar:?]
	at net.minecraft.class_128.handler$cap000$gameStarted(class_128.java:2016) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at carpetextra.CarpetExtraServer.<clinit>(CarpetExtraServer.java:26)
	at net.minecraft.class_128.handler$cap000$gameStarted(class_128.java:2016)
	at net.minecraft.class_128.method_24305(class_128.java)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [zoob.mixins.json:PlayerEntityMixin] from phase [DEFAULT] in config [zoob.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1657::addParticles with priority 1000 cannot inject into net/minecraft/class_1657::method_5773()V merged by thallium.fabric.mixins.general.MixinPlayerEntity with priority 1000 [PREINJECT Applicator Phase -> zoob.mixins.json:PlayerEntityMixin -> Prepare Injections ->  -> handler$def000$addParticles(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more
```

**Comment by JeffAxe123** [comment]
This mod is fake, it does not improve FPS, use sodium

**Comment by IsaiahPatton** [comment]
> 
> 
> This mod is fake, it does not improve FPS, use sodium
> https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec

Considering some optimizations are inspired from Paper and 1.12 Forge optimization mods, I would highly doubt that.

* [optimized entity collisions](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/thallium/fabric/mixins/general/MixinLivingEntity.java#L37) to fix redundant amount of raycasting (also in [Paper/Trunity](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0138-Cap-Entity-Collisions.patch), slightly modified)
* [hopper empty check](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/thallium/fabric/mixins/optimize_hopper/MixinHopperBlockEntity.java) (also in Paper)
* [Enguinecraft Redstone](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/redstone/RedstoneWireTurbo.java) (old known public faster redstone algorithm, added in [Paper](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0561-Optimize-redstone-algorithm.patch) 1.13),
* [isChuckLoad tick optimization](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/thallium/fabric/mixins/general/MixinClientPlayerEntity.java#L43) (from Trunity),
* [optimized animated textures](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/thallium/fabric/mixins/general/MixinSpriteAtlasTexture.java#L33) (inspired from the 1.12 VanillaFix forgemod, also found in Optifine)
* [Rewriten chuckmap](https://github.com/IsaiahMC/thallium/blob/master/src/main/java/thallium/fabric/chunk/FastChunkMap.java) to use Fastutil (also in [Paper](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0428-Optimize-PlayerChunkMap-memory-use-for-visibleChunks.patch#L22), and I believe Optifine too)
* Better statistic ticking with high player count (inspired by the one found [in Hydrinity](https://github.com/duplexsystem/Hydrinity/blob/master/patches/server/0016-Smarter-statistics-ticking.patch))
* Thallium [also improves the BipedEntityModel](https://github.com/IsaiahMC/thallium/blob/f8758b1adf9c01fc0b81e2cd5edb342411de2bd2/src/main/java/thallium/fabric/mixins/fastmath/MixinBipedEntityModel.java#L93) to not use sine/cosine computations for limb movement
And many more.

**Comment by IdrisQe** [comment]
> This mod is fake, it does not improve FPS, use sodium
> https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec


Yeah sure use Sodium which would break half the mods I'm using because it's incompatible with Fabric's entire rendering API... Genius! And this mod has very real improvements, not just for FPS, but potentially TPS as well, sooo...

If I could use Sodium I would be, obviously. There's no reason I wouldn't be using both mods honestly.
