### ISSUE TITLE
crash when using switched math algorithm 

### ISSUE THREAD

**Issue by DariusSG** [IsaiahMC/thallium#8]
Whenever I switch the math algorithm from riven(default) to ice-code, and I restart Minecraft, it crash. Probably because of the way you handle the config loading. 

Crash Report
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-08-14 19:00:13 SGT
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'thallium'!
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zze000$stopFabricInit(MinecraftClient:3291)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:425)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
    at thallium.fabric.gui.ThalliumOptions.load(ThalliumOptions.java:92)
    at thallium.fabric.ThalliumMod.onInitialize(ThalliumMod.java:28)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more

**Comment by Miros77** [comment]
delete thallium-options.dat
